all: first second

first:
	g++ -std=c++11 -DMH1=1 maxHeap2.cpp simulator.cpp -o simulator_Q2

second:
	g++ -std=c++11 -DMH2=1 maxHeap1.cpp simulator.cpp -o simulator_Q1	

clean:
	rm simulator_Q1 simulator_Q2